DROP TABLE IF EXISTS TB_MEMBER;

CREATE TABLE TB_MEMBER
(
  SEQ INT PRIMARY KEY AUTO_INCREMENT
 ,MBER_ID VARCHAR
 ,MBER_NM VARCHAR
 ,MBER_PW VARCHAR
 ,REG_DT DATE
);


DROP TABLE IF EXISTS TB_SEARCH_LOG;

CREATE TABLE TB_SEARCH_LOG
(
  SEQ INT PRIMARY KEY AUTO_INCREMENT
 ,MBER_ID VARCHAR
 ,KEYWORD VARCHAR
 ,REG_DT DATE
);
